package com.rhmsoft.codeund9013;

/* This class is generated by JADX */
public final class R {

    public static final class NP_MANAGER1 {
        public static final int MT_Bin = 2130771968;
    }

    public static final class NP_MANAGER2 {
        public static final int MT_Bin = 2130837504;
    }

    public static final class NP_MANAGER3 {
        public static final int MT_Bin = 2130903040;
    }

    public static final class NP_MANAGER4 {
        public static final int MT_Bin = 2130968576;
    }

    public static final class NP_MANAGER5 {
        public static final int MT_Bin = 2131034112;
    }

    public static final class NP_MANAGER6 {
        public static final int MT_Bin = 2131099648;
    }

    public static final class NP_MANAGER7 {
        public static final int MT_Bin = 2131165184;
    }

    public static final class NP_MANAGER8 {
        public static final int MT_Bin = 2131230720;
    }

    public static final class NP_MANAGER9 {
        public static final int MT_Bin = 2131296256;
    }

    public static final class NP_MANAGER10 {
        public static final int MT_Bin = 2131361792;
    }

    public static final class NP_MANAGER11 {
        public static final int MT_Bin = 2131427328;
    }

    public static final class NP_MANAGER12 {
        public static final int MT_Bin = 2131492864;
    }

    public static final class NP_MANAGER13 {
        public static final int MT_Bin = 2131558400;
    }

    public static final class NP_MANAGER14 {
        public static final int MT_Bin = 2131623936;
    }

    public static final class NP_MANAGER15 {
        public static final int MT_Bin = 2131689472;
    }

    public static final class NP_MANAGER17 {
        public static final int MT_Bin = 2131820544;
    }
}
